[package]
name = "reth-snapshot"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = """
Snapshotting implementation
"""

[dependencies]
# reth
reth-primitives.workspace = true
reth-db.workspace = true
reth-provider.workspace = true
reth-interfaces.workspace = true
reth-nippy-jar = { path = "../storage/nippy-jar" }

# async
tokio = { workspace = true, features = ["sync"] }

# misc
thiserror.workspace = true
tracing.workspace = true
clap = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
# reth
reth-db = { workspace = true, features = ["test-utils"] }
reth-stages = { path = "../stages", features = ["test-utils"] }

# misc

assert_matches.workspace = true

[features]
clap = ["dep:clap"]