[package]
name = "cli-extension-event-hooks"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true

[dependencies]
reth.workspace = true
clap.workspace = true
eyre.workspace = true
