[package]
name = "reth-codecs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
codecs-derive = { path = "./derive", default-features = false }

alloy-primitives.workspace = true
bytes.workspace = true

[dev-dependencies]
alloy-primitives = { workspace = true, features = ["arbitrary", "serde"] }
serde.workspace = true
modular-bitfield = "0.11.2"
test-fuzz = "4"

arbitrary = { workspace = true, features = ["derive"] }
proptest.workspace = true
proptest-derive.workspace = true

[features]
default = ["compact"]
compact = ["codecs-derive/compact"]
scale = ["codecs-derive/scale"]
postcard = ["codecs-derive/postcard"]
no_codec = ["codecs-derive/no_codec"]
optimism = ["codecs-derive/optimism"]