version: '3.9'
name: 'reth'

services:
  reth:
    restart: unless-stopped
    image: ghcr.io/paradigmxyz/reth
    ports:
      - '9001:9001' # metrics
      - '30303:30303' # eth/66 peering
      - '8545:8545' # rpc
      - '8551:8551' # engine
    volumes:
      - /Volumes/reth-daddy/reth-node/rethdata_mainnet:/root/.local/share/reth/mainnet/db
      - /Volumes/reth-daddy/reth-node/rethdata_sepolia:/root/.local/share/reth/sepolia/db
      - /Volumes/reth-daddy/reth-node/rethlogs:/root/rethlogs
      - /Volumes/reth-daddy/reth-node/reth/jwttoken:/root/jwt:ro
    # For Sepolia, replace `--chain mainnet` with `--chain sepolia`
    command: >
      node
      --chain mainnet
      --metrics 0.0.0.0:9001
      --log.file.directory /root/rethlogs
      --authrpc.addr 0.0.0.0
      --authrpc.port 8551
      --authrpc.jwtsecret /root/jwt/jwt.hex
      --http --http.addr 0.0.0.0 --http.port 8545
      --http.api "eth,net,web3"
       -vvvvv

  prometheus:
    restart: unless-stopped
    image: prom/prometheus
    depends_on:
      - reth
    ports:
      - 9090:9090
    volumes:
      - /Volumes/reth-daddy/reth-node/reth/prometheus/:/etc/prometheus/
      - /Volumes/reth-daddy/reth-node/prometheusdata:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus

  grafana:
    restart: unless-stopped
    image: grafana/grafana:10.1.0
    depends_on:
      - reth
      - prometheus
    ports:
      - 3000:3000
    environment:
      PROMETHEUS_URL: http://prometheus:9090
    volumes:
      - /Volumes/reth-daddy/reth-node/grafanadata:/var/lib/grafana
      - /Volumes/reth-daddy/reth-node/reth/grafana/datasources:/etc/grafana/provisioning/datasources
      - /Volumes/reth-daddy/reth-node/reth/grafana/dashboards:/etc/grafana/provisioning_temp/dashboards
    # 1. Copy dashboards from temp directory to prevent modifying original host files
    # 2. Replace Prometheus datasource placeholder with the actual name
    # 3. Run Grafana
    entrypoint: >
      sh -c "cp -r /etc/grafana/provisioning_temp/dashboards/. /etc/grafana/provisioning/dashboards &&
             find /etc/grafana/provisioning/dashboards/ -name '*.json' -exec sed -i 's/$${DS_PROMETHEUS}/Prometheus/g' {} \\+ &&
             /run.sh"