[package]
name = "additional-rpc-namespace-in-cli"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true

[dependencies]
reth.workspace = true
reth-transaction-pool.workspace = true

clap = { workspace = true, features = ["derive"] }
jsonrpsee = { workspace = true, features = ["server", "macros"] }
eyre.workspace = true

[dev-dependencies]
tokio.workspace = true
