[package]
name = "ef-tests"
version.workspace = true
description = "EF testing support for reth."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
ef-tests = []

[dependencies]
reth-primitives.workspace = true
reth-db = { workspace = true, features = ["mdbx", "test-utils"] }
reth-provider.workspace = true
reth-stages = { path = "../../crates/stages" }
reth-interfaces.workspace = true
reth-revm = { path = "../../crates/revm" }

alloy-rlp.workspace = true
tokio = "1.28.1"
walkdir = "2.3.3"
serde = "1.0.163"
serde_json.workspace = true
thiserror.workspace = true
