[package]
name = "reth-nippy-jar"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Immutable data store format"

[lib]
name = "reth_nippy_jar"

[dependencies]

# filter
ph = "0.8.0"
cuckoofilter = { version = "0.5.0", features = ["serde_support", "serde_bytes"] }

# compression
zstd = { version = "0.12", features = ["experimental", "zdict_builder"] }
lz4_flex = { version = "0.11", default-features = false }

# offsets
sucds = "~0.8"

memmap2 = "0.7.1"
bincode = "1.3"
serde = { version = "1.0",  features = ["derive"] }
bytes.workspace = true
tempfile.workspace = true
tracing = "0.1.0"
tracing-appender = "0.2"
anyhow = "1.0"
thiserror.workspace = true
hex = "*"

[dev-dependencies]
rand = { version = "0.8", features = ["small_rng"] }


[features]
default = []